name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Log into registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile.cpu --tag $IMAGE_NAME
    
    - name: Push image
      run: |
          IMAGE_ID=${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME
          
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          VERSION=$(echo $(date +%y.%m.%d) | tr '[A-Z]' '[a-z]')
          
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION-$IMAGE_TYPE
          
          docker push $IMAGE_ID:$VERSION-$IMAGE_TYPE
